title: "Jaime Echegaray"
description: "Operations & BI | Data Analytics Portfolio"
theme: jekyll-theme-minimal
show_downloads: false

author:
  name: "Jaime Echegaray"
  avatar: "/assets/image.jpeg"
  bio: "Business Intelligence & Operations professional transitioning into Data Analytics."

linkedin: "www.linkedin.com/in/jaime-e"
email: "jaime_echegaray_s@hotmail.com"
github: "https://github.com/Jaime-Analytics"
location: "Calgary & Bow Valley Region, Alberta"

plugins:
  - jekyll-seo-tag
