author:
  name: "Jaime Echegaray"
  avatar: "/assets/image.jpeg"

title: "Jaime Echegaray"
logo: "/assets/image.jpeg"
description: "Operations & BI | Data Analytics Portfolio"
show_downloads: false
theme: jekyll-theme-minimal
